spring.application.name=game-service
server.port=8083
spring.datasource.url=jdbc:postgresql://localhost:5433/myroblox_game
spring.datasource.username=myroblox_game
spring.datasource.password=myroblox123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true